name: Hello Charm Tests

on:
  push:
    branches:
      - main
  pull_request:
  workflow_call:

permissions: {}

jobs:
  hello-charm-tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - charm-repo: jnsgruk/hello-kubecon
            commit: eb3225860cc7db0e071d0ea6cd4a01b47e66b1e5  # 2025-03-27T12:05:21Z
          - charm-repo: juju/hello-juju-charm
            commit: 046b8ce758660d5aa9cf05207e2370fcbab688d0  # 2021-12-16T10:10:24Z
    steps:
      - name: Set up Python 3.10
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Checkout the ${{ matrix.charm-repo }} repository
        uses: actions/checkout@v5
        with:
          repository: ${{ matrix.charm-repo }}
          persist-credentials: false
          ref: ${{ matrix.commit }}

      - name: Remove 'ops' from charm requirements.txt
        run: |
          sed -i -e "/^ops[ ><=]/d" -e "/canonical\/operator/d" -e "/#egg=ops/d" requirements.txt
          TEST_OPS="git+$GITHUB_SERVER_URL/$GITHUB_REPOSITORY@$GITHUB_SHA#egg=ops"
          echo -e "\n${TEST_OPS}" >> requirements.txt

      - name: Install dependencies
        run: pip install -r requirements-dev.txt

      - name: Run the charm tests
        run: |
          export PYTHONPATH="lib:src:$PYTHONPATH"
          python3 -m unittest
