---
name: Publish
"on":
  push:
    tags:
      - '[1-3].*'

permissions: {}

jobs:
  build-and-publish:
    name: Build and publish to PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read
    environment: publish-pypi
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false
      - uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41  # v7.2.1
        with:
          enable-cache: false
      - run: uv build --all
      - name: Test if built package versions and dependency versions match
        run: |
          set -xueo pipefail
          uvx --with "$(echo -n dist/ops-*.whl)[testing,tracing]" --with dist/ops_scenario-*.whl --with dist/ops_tracing-*.whl python -c 'import ops, scenario, ops_tracing; print("OK")'
      - uses: actions/attest-build-provenance@v3
        with:
          subject-path: 'dist/*'
      - uses: pypa/gh-action-pypi-publish@release/v1

  secscan:
    uses: ./.github/workflows/sbom-secscan.yaml
