name: Publish (ops)
on:
  push:
    tags:
      # TODO: When we come to ops v3.x we will need to reconsider what to do
      # here (we might want to start prefixing with 'v' for one thing), and we
      # will likely be publishing at least three packages: ops, ops-scenario,
      # and ops-harness.
      - '2.*'

permissions: {}

jobs:
  build-n-publish:
    name: Build and Publish ops to PyPI
    runs-on: ubuntu-latest
    environment: publish-pypi
    permissions:
      id-token: write
      attestations: write
      contents: read
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683  # v4.2.2
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      - name: Install build dependencies
        run: pip install wheel build
      - name: Build
        run: python -m build
      - name: Attest build provenance
        uses: actions/attest-build-provenance@v2.2.3
        with:
          subject-path: 'dist/*'
      - name: Publish
        uses: pypa/gh-action-pypi-publish@release/v1
