name: Test Publish (ops)
on: [workflow_dispatch, workflow_call]

permissions: {}

jobs:
  build-n-publish:
    name: Build and Publish ops to Test PyPI
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      attestations: write
      contents: read
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065  # v5.6.0
      - name: Install build dependencies
        run: pip install wheel build
      - name: Build
        run: python -m build
      - name: Attest build provenance
        uses: actions/attest-build-provenance@db473fddc028af60658334401dc6fa3ffd8669fd  # v2.3.0
        with:
          subject-path: 'dist/*'
      - name: Publish to test.pypi.org
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository-url: https://test.pypi.org/legacy/
