name: TIOBE Quality Checks

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 1 * *'

permissions: {}

jobs:
  TICS:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

        # We could store the report from the regular run, but this is cheap to do and keeps this isolated.
      - uses: astral-sh/setup-uv@f0ec1fc3b38f5e7cd731bb6ce540c5af426746bb  # v6.1.0
      - run: uv tool install tox --with tox-uv

      - name: Generate coverage report
        run: tox -e coverage,coverage-tracing,coverage-report

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@009979693978bfefad2ad15c1020066694968dc7  # v3.4.0
        with:
          mode: qserver
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: operator
          installTics: true
