name: TIOBE Quality Checks

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * 0'

permissions: {}

jobs:
  TICS:
    runs-on: [self-hosted, reactive, amd64, tiobe, noble]
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

        # We could store the report from the regular run, but this is cheap to do and keeps this isolated.
      - uses: astral-sh/setup-uv@803947b9bd8e9f986429fa0c5a41c367cd732b41  # v7.2.1
      - run: uv tool install tox --with tox-uv

      - name: Generate coverage report
        run: tox -e coverage,coverage-tracing,coverage-report

      - name: Install TIOBE and project dependencies
        run: |
          uv export --no-emit-project --frozen --no-hashes --group unit --group lint --group release > requirements.txt
          pip install flake8 pylint -e . -r requirements.txt --break-system-packages

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@faf5066082a31b2517574270b45e3df92aa39a35  # v3.7.1
        with:
          mode: qserver
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: operator
          installTics: true
