name: TIOBE Quality Checks

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 7 * * 0'

permissions: {}

jobs:
  TICS:
    runs-on: [self-hosted, reactive, amd64, tiobe, noble]
    steps:
      - uses: actions/checkout@v5
        with:
          persist-credentials: false

        # We could store the report from the regular run, but this is cheap to do and keeps this isolated.
      - uses: astral-sh/setup-uv@1e862dfacbd1d6d858c55d9b792c756523627244  # v7.1.4
      - run: uv tool install tox --with tox-uv

      - name: Generate coverage report
        run: tox -e coverage,coverage-tracing,coverage-report

      - name: Install TIOBE and project dependencies
        run: |
          uv export --no-emit-project --frozen --no-hashes --group unit --group lint --group release > requirements.txt
          pip install flake8 pylint -e . -r requirements.txt --break-system-packages

      - name: TICS GitHub Action
        uses: tiobe/tics-github-action@427ef84d84bf35e39235d61406f414811bb99ce9  # v3.6.0
        with:
          mode: qserver
          viewerUrl: https://canonical.tiobe.com/tiobeweb/TICS/api/cfg?name=default
          ticsAuthToken: ${{ secrets.TICSAUTHTOKEN }}
          project: operator
          installTics: true
